site_name: "HEP-METADEX: High Energy Physics Metadata Exchange"
site_url: https://dune.github.io/hep-metadex/
repo_url: https://github.com/DUNE/hep-metadex
# repo_name: DUNE/hep-metadex

extra_css:
  - stylesheets/extra.css

theme:
  features:
    - content.action.view
    - navigation.footer

  icon:
    admonition:
      diagram: fontawesome/solid/diagram-project

    logo: material/hub-outline

    repo: fontawesome/brands/github

  name: material

  palette:
    scheme: slate

nav:
  - Home: "index.md"
  - Research Programs: "*include ./programs/*/mkdocs.yml"
  # - Research Programs:
  #     - DUNE: "!include ./programs/dune/mkdocs.yml"
  #     - ProtoDUNE: "!include ./programs/proto-dune/mkdocs.yml"
  # - v3: "!include ./v3/mkdocs.yml"

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - tables

plugins:
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - glightbox
  - monorepo
  - search
